/* MANUFACTURING ANALYTICS - MySQL PROJECT */

create database m_project;

use m_project;
select * from sqlproject;
alter table sqlproject change column ï»¿Buyer Buyer varchar(50);
select * from sqlproject;

SELECT COUNT(*) FROM sqlproject;

select * from sqlproject;

# TOTAL MANUFACTURED QUANTITY
SELECT SUM(`MANUFACTURED QTY`) AS TOTAL_MANUFACTURED_QTY FROM sqlproject;

# TOTAL REJECTED QUANTITY
SELECT SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY FROM sqlproject;

# TOTAL PROCESSED QUANTITY
SELECT SUM(`PROCESSED QTY`) AS TOTAL_PROCESSED_QTY FROM sqlproject;

# TOTAL WASTAGE QUANTITY
SELECT SUM(`WASTAGE QTY`) AS TOTAL_WASTAGE_QTY FROM sqlproject;

# MACHINEWISE REJECTED QUANTITY
SELECT `MACHINE NAME` AS MACHINE_NAME , SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY FROM sqlproject GROUP BY `MACHINE NAME`;

# EMPLOYEEWISE REJECTED QUANTITY
SELECT `EMP NAME` AS EMPLOYEE_NAME , SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY FROM sqlproject GROUP BY `EMP NAME`;

# DEPARTMENTWISE REJECTED QUANTITY
SELECT `DEPARTMENT NAME` AS DEPARTMENT_NAME , SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY FROM sqlproject GROUP BY `DEPARTMENT NAME`;

# MANUFACTURED VS REJECTED
SELECT SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY, SUM(`MANUFACTURED QTY`) AS TOTAL_MANUFACTURED_QTY FROM sqlproject;

# PRODUCTION COMPARISON TREND
SELECT DATE_ADD('1899-12-30', INTERVAL FLOOR(`DOC DATE`) DAY) + INTERVAL (`DOC DATE` - FLOOR(`DOC DATE`)) DAY as DOC_DATE,
`MANUFACTURED QTY` as TOTAL_MANUFACTURED_QTY,
`REJECTED QTY` as TOTAL_REJECTED_QTY,
`PROCESSED QTY` as TOTAL_PROCESSED_QTY
FROM sqlproject;
